POST http://localhost:3333/events
  Content-Type: application/json

  {
    "title" : "Bored Event",
    "description" : "Come see (or not, you know) the most bored things you've never ever seen before",
    "maximumAttendees" : null
  }